[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "alacritty-direct"

[font]
size = 12.0

[font.bold]
family = "JetBrains Mono"

[font.bold_italic]
family = "JetBrains Mono"

[font.italic]
family = "JetBrains Mono"

[font.normal]
family = "JetBrains Mono"

[general]
live_config_reload = true
import = [
  "~/.config/alacritty/github_light.toml",
  "~/.config/alacritty/work.toml",
]

[[hints.enabled]]
# Generic URLs
command = "open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[[keyboard.bindings]]
# disable creation of new tabs
key = "T"
mods = "Command"
action = "None"

[[keyboard.bindings]]
# disable creation of new windows
key = "N"
mods = "Command"
action = "None"

[mouse]
hide_when_typing = false

[scrolling]
history = 0
multiplier = 0

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
dynamic_padding = true
option_as_alt = "OnlyLeft"
